spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/azure_redis
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true