INSERT INTO country (code, name, created_at) VALUES ('AF' , 'Afghanistan', now());
INSERT INTO country (code, name, created_at) VALUES ('AX' , 'Aland Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('AL' , 'Albania', now());
INSERT INTO country (code, name, created_at) VALUES ('DZ' , 'Algeria', now());
INSERT INTO country (code, name, created_at) VALUES ('AS' , 'American Samoa', now());
INSERT INTO country (code, name, created_at) VALUES ('AD' , 'Andorra', now());
INSERT INTO country (code, name, created_at) VALUES ('AO' , 'Angola', now());
INSERT INTO country (code, name, created_at) VALUES ('AI' , 'Anguilla', now());
INSERT INTO country (code, name, created_at) VALUES ('AQ' , 'Antarctica', now());
INSERT INTO country (code, name, created_at) VALUES ('AG' , 'Antigua And Barbuda', now());
INSERT INTO country (code, name, created_at) VALUES ('AR' , 'Argentina', now());
INSERT INTO country (code, name, created_at) VALUES ('AM' , 'Armenia', now());
INSERT INTO country (code, name, created_at) VALUES ('AW' , 'Aruba', now());
INSERT INTO country (code, name, created_at) VALUES ('AU' , 'Australia', now());
INSERT INTO country (code, name, created_at) VALUES ('AT' , 'Austria', now());
INSERT INTO country (code, name, created_at) VALUES ('AZ' , 'Azerbaijan', now());
INSERT INTO country (code, name, created_at) VALUES ('BS' , 'Bahamas', now());
INSERT INTO country (code, name, created_at) VALUES ('BH' , 'Bahrain', now());
INSERT INTO country (code, name, created_at) VALUES ('BD' , 'Bangladesh', now());
INSERT INTO country (code, name, created_at) VALUES ('BB' , 'Barbados', now());
INSERT INTO country (code, name, created_at) VALUES ('BY' , 'Belarus', now());
INSERT INTO country (code, name, created_at) VALUES ('BE' , 'Belgium', now());
INSERT INTO country (code, name, created_at) VALUES ('BZ' , 'Belize', now());
INSERT INTO country (code, name, created_at) VALUES ('BJ' , 'Benin', now());
INSERT INTO country (code, name, created_at) VALUES ('BM' , 'Bermuda', now());
INSERT INTO country (code, name, created_at) VALUES ('BT' , 'Bhutan', now());
INSERT INTO country (code, name, created_at) VALUES ('BO' , 'Bolivia, Plurinational State Of', now());
INSERT INTO country (code, name, created_at) VALUES ('BA' , 'Bosnia And Herzegovina', now());
INSERT INTO country (code, name, created_at) VALUES ('BW' , 'Botswana', now());
INSERT INTO country (code, name, created_at) VALUES ('BV' , 'Bouvet Island', now());
INSERT INTO country (code, name, created_at) VALUES ('BR' , 'Brazil', now());
INSERT INTO country (code, name, created_at) VALUES ('IO' , 'British Indian Ocean Territory', now());
INSERT INTO country (code, name, created_at) VALUES ('BN' , 'Brunei Darussalam', now());
INSERT INTO country (code, name, created_at) VALUES ('BG' , 'Bulgaria', now());
INSERT INTO country (code, name, created_at) VALUES ('BF' , 'Burkina Faso', now());
INSERT INTO country (code, name, created_at) VALUES ('BI' , 'Burundi', now());
INSERT INTO country (code, name, created_at) VALUES ('KH' , 'Cambodia', now());
INSERT INTO country (code, name, created_at) VALUES ('CM' , 'Cameroon', now());
INSERT INTO country (code, name, created_at) VALUES ('CA' , 'Canada', now());
INSERT INTO country (code, name, created_at) VALUES ('CV' , 'Cape Verde', now());
INSERT INTO country (code, name, created_at) VALUES ('KY' , 'Cayman Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('CF' , 'Central African Republic', now());
INSERT INTO country (code, name, created_at) VALUES ('TD' , 'Chad', now());
INSERT INTO country (code, name, created_at) VALUES ('CL' , 'Chile', now());
INSERT INTO country (code, name, created_at) VALUES ('CN' , 'China', now());
INSERT INTO country (code, name, created_at) VALUES ('CX' , 'Christmas Island', now());
INSERT INTO country (code, name, created_at) VALUES ('CC' , 'Cocos (Keeling) Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('CO' , 'Colombia', now());
INSERT INTO country (code, name, created_at) VALUES ('KM' , 'Comoros', now());
INSERT INTO country (code, name, created_at) VALUES ('CG' , 'Congo', now());
INSERT INTO country (code, name, created_at) VALUES ('CD' , 'Congo The Democratic Republic', now());
INSERT INTO country (code, name, created_at) VALUES ('CK' , 'Cook Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('CR' , 'Costa Rica', now());
INSERT INTO country (code, name, created_at) VALUES ('CI' , 'Cote Dvoire', now());
INSERT INTO country (code, name, created_at) VALUES ('HR' , 'Croatia', now());
INSERT INTO country (code, name, created_at) VALUES ('CU' , 'Cuba', now());
INSERT INTO country (code, name, created_at) VALUES ('CY' , 'Cyprus', now());
INSERT INTO country (code, name, created_at) VALUES ('CZ' , 'Czech Republic', now());
INSERT INTO country (code, name, created_at) VALUES ('DK' , 'Denmark', now());
INSERT INTO country (code, name, created_at) VALUES ('DJ' , 'Djibouti', now());
INSERT INTO country (code, name, created_at) VALUES ('DM' , 'Dominica', now());
INSERT INTO country (code, name, created_at) VALUES ('DO' , 'Dominican Republic', now());
INSERT INTO country (code, name, created_at) VALUES ('EC' , 'Ecuador', now());
INSERT INTO country (code, name, created_at) VALUES ('EG' , 'Egypt', now());
INSERT INTO country (code, name, created_at) VALUES ('SV' , 'El Salvador', now());
INSERT INTO country (code, name, created_at) VALUES ('GQ' , 'Equatorial Guinea', now());
INSERT INTO country (code, name, created_at) VALUES ('ER' , 'Eritrea', now());
INSERT INTO country (code, name, created_at) VALUES ('EE' , 'Estonia', now());
INSERT INTO country (code, name, created_at) VALUES ('ET' , 'Ethiopia', now());
INSERT INTO country (code, name, created_at) VALUES ('FK' , 'Falkland Islands (Malvinas)', now());
INSERT INTO country (code, name, created_at) VALUES ('FO' , 'Faroe Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('FJ' , 'Fiji', now());
INSERT INTO country (code, name, created_at) VALUES ('FI' , 'Finland', now());
INSERT INTO country (code, name, created_at) VALUES ('FR' , 'France', now());
INSERT INTO country (code, name, created_at) VALUES ('GF' , 'French Guiana', now());
INSERT INTO country (code, name, created_at) VALUES ('PF' , 'French Polynesia', now());
INSERT INTO country (code, name, created_at) VALUES ('TF' , 'French Southern Territories', now());
INSERT INTO country (code, name, created_at) VALUES ('GA' , 'Gabon', now());
INSERT INTO country (code, name, created_at) VALUES ('GM' , 'Gambia', now());
INSERT INTO country (code, name, created_at) VALUES ('GE' , 'Georgia', now());
INSERT INTO country (code, name, created_at) VALUES ('DE' , 'Germany', now());
INSERT INTO country (code, name, created_at) VALUES ('GH' , 'Ghana', now());
INSERT INTO country (code, name, created_at) VALUES ('GI' , 'Gibraltar', now());
INSERT INTO country (code, name, created_at) VALUES ('GR' , 'Greece', now());
INSERT INTO country (code, name, created_at) VALUES ('GL' , 'Greenland', now());
INSERT INTO country (code, name, created_at) VALUES ('GD' , 'Grenada', now());
INSERT INTO country (code, name, created_at) VALUES ('GP' , 'Guadeloupe', now());
INSERT INTO country (code, name, created_at) VALUES ('GU' , 'Guam', now());
INSERT INTO country (code, name, created_at) VALUES ('GT' , 'Guatemala', now());
INSERT INTO country (code, name, created_at) VALUES ('GG' , 'Guernsey', now());
INSERT INTO country (code, name, created_at) VALUES ('GN' , 'Guinea', now());
INSERT INTO country (code, name, created_at) VALUES ('GW' , 'Guinea-Bissau', now());
INSERT INTO country (code, name, created_at) VALUES ('GY' , 'Guyana', now());
INSERT INTO country (code, name, created_at) VALUES ('HT' , 'Haiti', now());
INSERT INTO country (code, name, created_at) VALUES ('HM' , 'Heard Island And Mcdonald', now());
INSERT INTO country (code, name, created_at) VALUES ('VA' , 'Holy See (Vatican City State)', now());
INSERT INTO country (code, name, created_at) VALUES ('HN' , 'Honduras', now());
INSERT INTO country (code, name, created_at) VALUES ('HK' , 'Hong Kong', now());
INSERT INTO country (code, name, created_at) VALUES ('HU' , 'Hungary', now());
INSERT INTO country (code, name, created_at) VALUES ('IS' , 'Iceland', now());
INSERT INTO country (code, name, created_at) VALUES ('IN' , 'India', now());
INSERT INTO country (code, name, created_at) VALUES ('ID' , 'Indonesia', now());
INSERT INTO country (code, name, created_at) VALUES ('IR' , 'Iran, Islamic Republic Of', now());
INSERT INTO country (code, name, created_at) VALUES ('IQ' , 'Iraq', now());
INSERT INTO country (code, name, created_at) VALUES ('IE' , 'Ireland', now());
INSERT INTO country (code, name, created_at) VALUES ('IM' , 'Isle Of Man', now());
INSERT INTO country (code, name, created_at) VALUES ('IL' , 'Israel', now());
INSERT INTO country (code, name, created_at) VALUES ('IT' , 'Italy', now());
INSERT INTO country (code, name, created_at) VALUES ('JM' , 'Jamaica', now());
INSERT INTO country (code, name, created_at) VALUES ('JP' , 'Japan', now());
INSERT INTO country (code, name, created_at) VALUES ('JE' , 'Jersey', now());
INSERT INTO country (code, name, created_at) VALUES ('JO' , 'Jordan', now());
INSERT INTO country (code, name, created_at) VALUES ('KZ' , 'Kazakhstan', now());
INSERT INTO country (code, name, created_at) VALUES ('KE' , 'Kenya', now());
INSERT INTO country (code, name, created_at) VALUES ('KI' , 'Kiribati', now());
INSERT INTO country (code, name, created_at) VALUES ('KP' , "Korea, Democratic People'S Republic Of", now());
INSERT INTO country (code, name, created_at) VALUES ('KR' , 'Korea, Republic Of', now());
INSERT INTO country (code, name, created_at) VALUES ('KW' , 'Kuwait', now());
INSERT INTO country (code, name, created_at) VALUES ('KG' , 'Kyrgyzstan', now());
INSERT INTO country (code, name, created_at) VALUES ('LA' , "Lao People'S Democratic Republic", now());
INSERT INTO country (code, name, created_at) VALUES ('LV' , 'Latvia', now());
INSERT INTO country (code, name, created_at) VALUES ('LB' , 'Lebanon', now());
INSERT INTO country (code, name, created_at) VALUES ('LS' , 'Lesotho', now());
INSERT INTO country (code, name, created_at) VALUES ('LR' , 'Liberia', now());
INSERT INTO country (code, name, created_at) VALUES ('LY' , 'Libyan Arab Jamahiriya', now());
INSERT INTO country (code, name, created_at) VALUES ('LI' , 'Liechtenstein', now());
INSERT INTO country (code, name, created_at) VALUES ('LT' , 'Lithuania', now());
INSERT INTO country (code, name, created_at) VALUES ('LU' , 'Luxembourg', now());
INSERT INTO country (code, name, created_at) VALUES ('MO' , 'Macao', now());
INSERT INTO country (code, name, created_at) VALUES ('MK' , 'Macedonia, The Former Yugoslav Republic Of', now());
INSERT INTO country (code, name, created_at) VALUES ('MG' , 'Madagascar', now());
INSERT INTO country (code, name, created_at) VALUES ('MW' , 'Malawi', now());
INSERT INTO country (code, name, created_at) VALUES ('MY' , 'Malaysia', now());
INSERT INTO country (code, name, created_at) VALUES ('MV' , 'Maldives', now());
INSERT INTO country (code, name, created_at) VALUES ('ML' , 'Mali', now());
INSERT INTO country (code, name, created_at) VALUES ('MT' , 'Malta', now());
INSERT INTO country (code, name, created_at) VALUES ('MH' , 'Marshall Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('MQ' , 'Martinique', now());
INSERT INTO country (code, name, created_at) VALUES ('MR' , 'Mauritania', now());
INSERT INTO country (code, name, created_at) VALUES ('MU' , 'Mauritius', now());
INSERT INTO country (code, name, created_at) VALUES ('YT' , 'Mayotte', now());
INSERT INTO country (code, name, created_at) VALUES ('MX' , 'Mexico', now());
INSERT INTO country (code, name, created_at) VALUES ('FM' , 'Micronesia, Federated States Of', now());
INSERT INTO country (code, name, created_at) VALUES ('MD' , 'Moldova, Republic Of', now());
INSERT INTO country (code, name, created_at) VALUES ('MC' , 'Monaco', now());
INSERT INTO country (code, name, created_at) VALUES ('MN' , 'Mongolia', now());
INSERT INTO country (code, name, created_at) VALUES ('ME' , 'Montenegro', now());
INSERT INTO country (code, name, created_at) VALUES ('MS' , 'Montserrat', now());
INSERT INTO country (code, name, created_at) VALUES ('MA' , 'Morocco', now());
INSERT INTO country (code, name, created_at) VALUES ('MZ' , 'Mozambique', now());
INSERT INTO country (code, name, created_at) VALUES ('MM' , 'Myanmar', now());
INSERT INTO country (code, name, created_at) VALUES ('NA' , 'Namibia', now());
INSERT INTO country (code, name, created_at) VALUES ('NR' , 'Nauru', now());
INSERT INTO country (code, name, created_at) VALUES ('NP' , 'Nepal', now());
INSERT INTO country (code, name, created_at) VALUES ('NL' , 'Netherlands', now());
INSERT INTO country (code, name, created_at) VALUES ('AN' , 'Netherlands Antilles', now());
INSERT INTO country (code, name, created_at) VALUES ('NC' , 'New Caledonia', now());
INSERT INTO country (code, name, created_at) VALUES ('NZ' , 'New Zealand', now());
INSERT INTO country (code, name, created_at) VALUES ('NI' , 'Nicaragua', now());
INSERT INTO country (code, name, created_at) VALUES ('NE' , 'Niger', now());
INSERT INTO country (code, name, created_at) VALUES ('NG' , 'Nigeria', now());
INSERT INTO country (code, name, created_at) VALUES ('NU' , 'Niue', now());
INSERT INTO country (code, name, created_at) VALUES ('NF' , 'Norfolk Island', now());
INSERT INTO country (code, name, created_at) VALUES ('MP' , 'Northern Mariana Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('NO' , 'Norway', now());
INSERT INTO country (code, name, created_at) VALUES ('OM' , 'Oman', now());
INSERT INTO country (code, name, created_at) VALUES ('PK' , 'Pakistan', now());
INSERT INTO country (code, name, created_at) VALUES ('PW' , 'Palau', now());
INSERT INTO country (code, name, created_at) VALUES ('PS' , 'Palestinian Territory, Occupied', now());
INSERT INTO country (code, name, created_at) VALUES ('PA' , 'Panama', now());
INSERT INTO country (code, name, created_at) VALUES ('PG' , 'Papua New Guinea', now());
INSERT INTO country (code, name, created_at) VALUES ('PY' , 'Paraguay', now());
INSERT INTO country (code, name, created_at) VALUES ('PE' , 'Peru', now());
INSERT INTO country (code, name, created_at) VALUES ('PH' , 'Philippines', now());
INSERT INTO country (code, name, created_at) VALUES ('PN' , 'Pitcairn', now());
INSERT INTO country (code, name, created_at) VALUES ('PL' , 'Poland', now());
INSERT INTO country (code, name, created_at) VALUES ('PT' , 'Portugal', now());
INSERT INTO country (code, name, created_at) VALUES ('PR' , 'Puerto Rico', now());
INSERT INTO country (code, name, created_at) VALUES ('QA' , 'Qatar', now());
INSERT INTO country (code, name, created_at) VALUES ('RE' , 'Reunion', now());
INSERT INTO country (code, name, created_at) VALUES ('RO' , 'Romania', now());
INSERT INTO country (code, name, created_at) VALUES ('RU' , 'Russian Federation', now());
INSERT INTO country (code, name, created_at) VALUES ('RW' , 'Rwanda', now());
INSERT INTO country (code, name, created_at) VALUES ('BL' , 'Saint Barthelemy', now());
INSERT INTO country (code, name, created_at) VALUES ('SH' , 'Saint Helena', now());
INSERT INTO country (code, name, created_at) VALUES ('KN' , 'Saint Kitts And Nevis', now());
INSERT INTO country (code, name, created_at) VALUES ('LC' , 'Saint Lucia', now());
INSERT INTO country (code, name, created_at) VALUES ('MF' , 'Saint Martin', now());
INSERT INTO country (code, name, created_at) VALUES ('PM' , 'Saint Pierre And Miquelon', now());
INSERT INTO country (code, name, created_at) VALUES ('VC' , 'Saint Vincent And The Grenadines', now());
INSERT INTO country (code, name, created_at) VALUES ('WS' , 'Samoa', now());
INSERT INTO country (code, name, created_at) VALUES ('SM' , 'San Marino', now());
INSERT INTO country (code, name, created_at) VALUES ('ST' , 'Sao Tome And Principe', now());
INSERT INTO country (code, name, created_at) VALUES ('SA' , 'Saudi Arabia', now());
INSERT INTO country (code, name, created_at) VALUES ('SN' , 'Senegal', now());
INSERT INTO country (code, name, created_at) VALUES ('RS' , 'Serbia', now());
INSERT INTO country (code, name, created_at) VALUES ('SC' , 'Seychelles', now());
INSERT INTO country (code, name, created_at) VALUES ('SL' , 'Sierra Leone', now());
INSERT INTO country (code, name, created_at) VALUES ('SG' , 'Singapore', now());
INSERT INTO country (code, name, created_at) VALUES ('SK' , 'Slovakia', now());
INSERT INTO country (code, name, created_at) VALUES ('SI' , 'Slovenia', now());
INSERT INTO country (code, name, created_at) VALUES ('SB' , 'Solomon Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('SO' , 'Somalia', now());
INSERT INTO country (code, name, created_at) VALUES ('ZA' , 'South Africa', now());
INSERT INTO country (code, name, created_at) VALUES ('GS' , 'South Georgia And The South Sandwich Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('ES' , 'Spain', now());
INSERT INTO country (code, name, created_at) VALUES ('LK' , 'Sri Lanka', now());
INSERT INTO country (code, name, created_at) VALUES ('SD' , 'Sudan', now());
INSERT INTO country (code, name, created_at) VALUES ('SR' , 'Suriname', now());
INSERT INTO country (code, name, created_at) VALUES ('SJ' , 'Svalbard And Jan Mayen', now());
INSERT INTO country (code, name, created_at) VALUES ('SZ' , 'Swaziland', now());
INSERT INTO country (code, name, created_at) VALUES ('SE' , 'Sweden', now());
INSERT INTO country (code, name, created_at) VALUES ('CH' , 'Switzerland', now());
INSERT INTO country (code, name, created_at) VALUES ('SY' , 'Syrian Arab Republic', now());
INSERT INTO country (code, name, created_at) VALUES ('TW' , 'Taiwan, Province Of China', now());
INSERT INTO country (code, name, created_at) VALUES ('TJ' , 'Tajikistan', now());
INSERT INTO country (code, name, created_at) VALUES ('TZ' , 'Tanzania, United Republic Of', now());
INSERT INTO country (code, name, created_at) VALUES ('TH' , 'Thailand', now());
INSERT INTO country (code, name, created_at) VALUES ('TL' , 'Timor-Leste', now());
INSERT INTO country (code, name, created_at) VALUES ('TG' , 'Togo', now());
INSERT INTO country (code, name, created_at) VALUES ('TK' , 'Tokelau', now());
INSERT INTO country (code, name, created_at) VALUES ('TO' , 'Tonga', now());
INSERT INTO country (code, name, created_at) VALUES ('TT' , 'Trinidad And Tobago', now());
INSERT INTO country (code, name, created_at) VALUES ('TN' , 'Tunisia', now());
INSERT INTO country (code, name, created_at) VALUES ('TR' , 'Turkey', now());
INSERT INTO country (code, name, created_at) VALUES ('TM' , 'Turkmenistan', now());
INSERT INTO country (code, name, created_at) VALUES ('TC' , 'Turks And Caicos Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('TV' , 'Tuvalu', now());
INSERT INTO country (code, name, created_at) VALUES ('UG' , 'Uganda', now());
INSERT INTO country (code, name, created_at) VALUES ('UA' , 'Ukraine', now());
INSERT INTO country (code, name, created_at) VALUES ('AE' , 'United Arab Emirates', now());
INSERT INTO country (code, name, created_at) VALUES ('GB' , 'United Kingdom', now());
INSERT INTO country (code, name, created_at) VALUES ('US' , 'United States', now());
INSERT INTO country (code, name, created_at) VALUES ('UM' , 'United States Minor Outlying Islands', now());
INSERT INTO country (code, name, created_at) VALUES ('UY' , 'Uruguay', now());
INSERT INTO country (code, name, created_at) VALUES ('UZ' , 'Uzbekistan', now());
INSERT INTO country (code, name, created_at) VALUES ('VU' , 'Vanuatu', now());
INSERT INTO country (code, name, created_at) VALUES ('VE' , 'Venezuela, Bolivarian Republic Of', now());
INSERT INTO country (code, name, created_at) VALUES ('VN' , 'Vietnam', now());
INSERT INTO country (code, name, created_at) VALUES ('VG' , 'Virgin Islands, British', now());
INSERT INTO country (code, name, created_at) VALUES ('VI' , 'Virgin Islands, U.S.', now());
INSERT INTO country (code, name, created_at) VALUES ('WF' , 'Wallis And Futuna', now());
INSERT INTO country (code, name, created_at) VALUES ('EH' , 'Western Sahara', now());
INSERT INTO country (code, name, created_at) VALUES ('YE' , 'Yemen', now());
INSERT INTO country (code, name, created_at) VALUES ('ZM' , 'Zambia', now());
INSERT INTO country (code, name, created_at) VALUES ('ZW' , 'Zimbabwe', now());